// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUKBOBS6O8N3rR2MtlLsS9nlrGRp2lVY0',
    appId: '1:198995196265:web:11a566fec2d5282a5965f8',
    messagingSenderId: '198995196265',
    projectId: 'infoassistant-aceb6',
    authDomain: 'infoassistant-aceb6.firebaseapp.com',
    storageBucket: 'infoassistant-aceb6.firebasestorage.app',
    measurementId: 'G-QVLXNYZJJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzxiC92MJhpwc7c5whDZKfSdKr5FYy0FQ',
    appId: '1:198995196265:android:67ecbc9b9aaf653f5965f8',
    messagingSenderId: '198995196265',
    projectId: 'infoassistant-aceb6',
    storageBucket: 'infoassistant-aceb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1EDQsF5NoAMOCBhzViB4mV-aMla8r1Iw',
    appId: '1:198995196265:ios:15c490e8070cd30d5965f8',
    messagingSenderId: '198995196265',
    projectId: 'infoassistant-aceb6',
    storageBucket: 'infoassistant-aceb6.firebasestorage.app',
    iosClientId: '198995196265-0jsb28i06i0edq11g4ke5114bukri842.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoassistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUKBOBS6O8N3rR2MtlLsS9nlrGRp2lVY0',
    appId: '1:198995196265:web:11a566fec2d5282a5965f8',
    messagingSenderId: '198995196265',
    projectId: 'infoassistant-aceb6',
    authDomain: 'infoassistant-aceb6.firebaseapp.com',
    storageBucket: 'infoassistant-aceb6.firebasestorage.app',
    measurementId: 'G-QVLXNYZJJJ',
  );
}
